### ISSUE TITLE
Some functions are missing

### ISSUE THREAD

**Issue by ZhengguoTan** [daiep/JULEP#1]
Dear Erpeng,

Thanks for sharing this excellent toolbox. 

As far as I can see, the following functions seem not included in the current repository: crop, fftc, and ifftc.

It would be great if you can help to check this.

Best Regards,
Zhengguo

**Comment by daiep** [comment]
Thanks for reporting this Dr. Tan. I have re-uploaded these functions. Please see whether they can work for you. Thanks. 

Erpeng

**Comment by ZhengguoTan** [comment]
Thanks Erpeng!
